repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: maven-compile
        name: Maven Compile
        entry: mvn -q compile
        language: system
        types: [java]
        pass_filenames: false
      # - id: maven-test
      #   name: Maven Test
      #   entry: mvn -q test
      #   language: system
      #   types: [java]
      #   pass_filenames: false
