services:
  # Database
  db:
    image: mariadb:10.11
    container_name: hcms-v2-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hcms
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hcms-network
    restart: always

  # Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hcms-v2-be
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hcms
      DB_USERNAME: root
      DB_PASSWORD: root
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - hcms-network
    restart: always

networks:
  hcms-network:
    name: hcms-global-network
    driver: bridge
